### PR TITLE
Apply changes to bind record type values to `anydata`

### LINKED ISSUE #7619: Unable to bind `record` type values as `anydata` in the Avro module
### Description

When using the `fromAvro()` API in the Avro module, it should infer the given type and bind the response into that value. When the response is returned as a `record` type, it can only be mapped into the record which matches exactly with the response.

Even the type is given as `anydata`, the value should be correctly mapped to `anydata` and returns the value. But here it returns a casting error.

### Steps to Reproduce

Use the following code snippet to try it.

```ballerina
    Student student = {
        name: "Liam",
        subject: "geology"
    };
    Schema avro = check new (schema);
    byte[] serializedValue = check avro.toAvro(student);
    anydata deserializedValue = check avro.fromAvro(serializedValue);
```

### Version

1.1.0, 1.0.0

### Environment Details (with versions)

_No response_

### PR DESCRIPTION
**Pull request by Nuvindu**

### CODE REVIEW

File: native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java [hunk 1]
```diff
@@ -83,7 +83,8 @@ public BMap<BString, Object> visit(RecordDeserializer recordDeserializer, Generi
         Type originalType = recordDeserializer.getType();
         Type type = recordDeserializer.getType();
         Schema schema = recordDeserializer.getSchema();
-        BMap<BString, Object> avroRecord = createAvroRecord(type);
+        BMap<BString, Object> avroRecord = (type.getTag() == TypeTags.ANYDATA_TAG)
```
Comment (ayeshLK) [inline native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java]: Shouldn't this logic go into the `createAvroRecord` method ?

File: native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java [hunk 2]
```diff
@@ -113,6 +114,9 @@ public BMap<BString, Object> visit(RecordDeserializer recordDeserializer, Generi
         if (originalType.isReadOnly()) {
             avroRecord.freezeDirect();
         }
+        if (type.getTag() == TypeTags.ANYDATA_TAG) {
+            return (BMap<BString, Object>) ValueUtils.convert(avroRecord, type);
```
Comment (ayeshLK) [inline native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java:119]: In L86 the `avroRecord` has been already defined as `BMap` (with this specific key-value types), why do we need to convert it back ?

File: native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java [hunk 3]
```diff
@@ -83,7 +83,8 @@ public BMap<BString, Object> visit(RecordDeserializer recordDeserializer, Generi
         Type originalType = recordDeserializer.getType();
         Type type = recordDeserializer.getType();
         Schema schema = recordDeserializer.getSchema();
-        BMap<BString, Object> avroRecord = createAvroRecord(type);
+        BMap<BString, Object> avroRecord = (type.getTag() == TypeTags.ANYDATA_TAG)
+                ? ValueCreator.createMapValue() : createAvroRecord(type);
```
Comment (daneshk) [inline native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java]: Can't we create a map value passing the type, here?

File: native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java (hunk 2 above)
Comment (Nuvindu) [reply native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java:119]: It's not converting back. Here the `BMap` value is converting to the `BAnydataType`. Without applying this, I'm getting a casting issue

File: native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java (hunk 3 above)
Comment (Nuvindu) [reply native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java]: There are some complex types like `record{} & readonly`, where we cannot use the `BMap` value directly. Because value creation fails for `readonly` type.

File: native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java (hunk 2 above)
Comment (ayeshLK) [reply native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java:119]: Ack. Better to check if we can directly create an `anydata` type using `ValueCreator` itself.

Comment (Nuvindu) [reply native/src/main/java/io/ballerina/lib/avro/deserialize/visitor/DeserializeVisitor.java:119]: Fixed in a11a0c9

**Review by daneshk — APPROVED** [review]
